import { Link } from "react-router-dom";
import CookiePreferences from "../components/editorial/CookiePreferences";

const contact = <a href="mailto:contact@cobalithstudio.fr">contact@cobalithstudio.fr</a>;
function LegalPage({ number, title, intro, children }) {
  return <section className="ce-policy ce-wrap">
    <header className="ce-policy-heading"><p className="ce-label">COBALITH STUDIO / {number}</p><h1>{title}</h1><p>{intro}</p></header>
    <div className="ce-policy-layout">
      <nav aria-label="Documents du site"><Link to="/mentions-legales">01 / Mentions légales</Link><Link to="/conditions-utilisation">02 / Conditions d’utilisation</Link><Link to="/confidentialite">03 / Confidentialité & cookies</Link></nav>
      <div className="ce-policy-copy"><aside className="ce-policy-draft"><strong>Version de travail — avant publication</strong><p>Le passage à une société est en préparation. L’identité de l’exploitant et les informations signalées ci-dessous doivent être confirmées. Ces documents ne constituent pas encore une version juridique finalisée.</p></aside>{children}</div>
    </div>
  </section>;
}
export function LegalNoticePage() {
  return <LegalPage number="01 / INFORMATIONS" title="Mentions légales." intro="Les informations relatives à l’édition du site de Cobalith Studio.">
    <section><h2>Le site</h2><p>Cobalith Studio présente son premier jeu, <em>Millésime : The Mastercut</em>, et donne accès à un espace de travail réservé aux comptes autorisés.</p><p>Contact : {contact}.</p></section>
    <section><h2>Éditeur & publication</h2><p>À confirmer avant publication : exploitant actuel du site, raison sociale, forme juridique, capital social, siège, SIREN et immatriculation applicable, coordonnées publiques et responsable de publication. Le numéro de TVA sera indiqué s’il est applicable.</p><p>Les identifiants de l’association précédemment mentionnée sur le site ne sont pas présentés comme ceux de la future société.</p></section>
    <section><h2>Hébergement</h2><p>Le projet est configuré pour un déploiement sur GitHub Pages. Le service effectivement retenu, la dénomination de l’hébergeur, son adresse et son numéro de téléphone restent à confirmer avant publication.</p></section>
    <section><h2>Contenus & liens</h2><p>Les textes, visuels et éléments du jeu sont soumis aux droits de leurs titulaires respectifs. Pour une demande de réutilisation, contactez le studio. Les sites externes accessibles par lien disposent de leurs propres conditions.</p><p><Link to="/confidentialite">Données personnelles et stockage dans le navigateur →</Link></p></section>
  </LegalPage>;
}
export function TermsPage() {
  return <LegalPage number="02 / UTILISATION" title="Conditions d’utilisation." intro="Un cadre simple pour consulter le projet et accéder à votre compte.">
    <section><h2>Présentation du projet</h2><p>Ce site présente Cobalith Studio et <em>Millésime : The Mastercut</em>. Les éléments d’un jeu en développement peuvent évoluer ; les présentations ne constituent pas une promesse de disponibilité à une date donnée.</p></section>
    <section><h2>Compte & accès équipe</h2><p>La connexion est destinée aux comptes validés par le studio. La création d’un compte n’accorde pas automatiquement l’accès aux espaces internes. Gardez vos identifiants confidentiels et signalez un accès suspect à {contact}.</p><p>N’essayez pas de contourner les restrictions d’accès, d’accéder aux données d’autrui ou de perturber le fonctionnement du site.</p></section>
    <section><h2>Utilisation des contenus</h2><p>La consultation du site ne transfère aucun droit sur le jeu, les illustrations, les marques ou les autres contenus. Toute réutilisation doit respecter les autorisations applicables et les exceptions prévues par la loi.</p></section>
    <section><h2>Le jeu sur Steam</h2><p>Le jeu est destiné à être vendu sur Steam. Ce site ne propose actuellement ni achat du jeu ni paiement. Les conditions applicables à un achat sur Steam seront celles présentées lors de cette transaction.</p></section>
    <section><h2>Disponibilité & contact</h2><p>Des interruptions peuvent survenir, notamment lors de la maintenance. Pour signaler une difficulté ou poser une question : {contact}.</p><p>Les dispositions légales impératives restent applicables. Les informations sur l’exploitant sont regroupées dans les <Link to="/mentions-legales">mentions légales</Link>.</p></section>
  </LegalPage>;
}
export function PrivacyPage() {
  return <LegalPage number="03 / VOS DONNÉES" title="Confidentialité & cookies." intro="Ce que le site utilise, pour quelles fonctions, et comment nous contacter.">
    <section><h2>Responsable du traitement</h2><p>L’entité juridiquement responsable doit être confirmée dans les <Link to="/mentions-legales">mentions légales</Link> avant publication. Pour toute question relative aux données : {contact}.</p></section>
    <section><h2>Les données concernées</h2><dl><dt>Navigation</dt><dd>Le code du site n’intègre pas de mesure d’audience ni de publicité. L’hébergeur peut traiter des données techniques de requête, notamment l’adresse IP, pour servir et sécuriser le site.</dd><dt>Contact par e-mail</dt><dd>Le lien de contact ouvre votre messagerie. L’adresse d’expédition et les informations que vous choisissez d’envoyer permettent de vous répondre ; il n’y a pas de formulaire de contact sur le site.</dd><dt>Création de compte & connexion</dt><dd>L’adresse e-mail et le mot de passe sont transmis au service d’authentification Supabase. Le profil contient notamment un identifiant, l’e-mail, le rôle, le statut d’accès et une date de création. Les champs du formulaire sont nécessaires à la demande d’accès ou à la connexion.</dd><dt>Espace équipe</dt><dd>Les espaces autorisés permettent d’enregistrer des informations et fichiers de travail. Leur accès reste soumis aux droits du compte.</dd></dl></section>
    <section><h2>Prestataires & destinataires</h2><p>Les services concernés sont l’hébergement du site, Supabase pour l’authentification et les données de l’espace équipe, et la messagerie pour les échanges directs. Les personnes habilitées du studio accèdent aux informations nécessaires à leurs fonctions.</p><p>À confirmer avant publication : prestataire de messagerie, régions d’hébergement, destinataires exacts et éventuels transferts hors de l’Espace économique européen ainsi que leurs garanties.</p></section>
    <section><h2>Finalités & conservation</h2><p>Les usages identifiés sont la fourniture du site, la réponse aux messages, la gestion des comptes et la collaboration interne.</p><p>À préciser avant publication, pour chaque usage : base légale retenue, durée de conservation ou critères de durée, et modalités effectives de suppression, y compris pour les sauvegardes. Aucune durée de suppression automatique n’est annoncée sans vérification.</p></section>
    <section><h2>Cookies & stockage local</h2><p>Supabase conserve la session de connexion dans le navigateur afin de maintenir l’accès au compte. Ce stockage est strictement nécessaire. Vous pouvez vous déconnecter pour mettre fin à la session locale ; cette action ne supprime pas le compte.</p><p>Le choix du bandeau est enregistré pendant six mois sous la clé « cobalith.cookie-preferences ». Accepter et refuser ont la même durée. La fermeture du bandeau ou la poursuite de navigation ne valent pas consentement.</p><p>Avec votre accord, notre mesure d’audience interne enregistre dans Supabase : pages et titres consultés, sessions et visiteurs pseudonymes, durée active, engagement, profondeur de lecture, page d’entrée, domaine référent, paramètres UTM source/medium/campaign, catégorie d’appareil, navigateur, système, tranche de largeur, langue, fuseau, type de connexion et indicateurs LCP/CLS. Elle n’enregistre pas l’adresse IP dans la table d’audience, l’agent utilisateur brut, l’identité du compte, les contenus saisis, l’URL complète ou une empreinte numérique.</p><p>Les identifiants pseudonymes restent au maximum treize mois sans prolongation automatique. Les événements bruts sont supprimés après vingt-cinq mois. Les données servent exclusivement à comprendre la fréquentation, les parcours et les performances de ce site. Elles ne sont ni vendues, ni utilisées pour la publicité, ni croisées avec d’autres sites. Les administrateurs autorisés du studio sont les seuls à pouvoir consulter la table d’audience.</p><p>Vous pouvez retirer votre accord à tout moment via « Cookies ». La révocation arrête la collecte et supprime les identifiants d’audience du navigateur ; les statistiques déjà reçues restent conservées pour la durée annoncée. Pour demander l’accès ou l’effacement d’événements liés à votre identifiant pseudonyme, contactez le studio avant de supprimer le stockage local.</p><CookiePreferences /></section>
    <section><h2>Vos droits</h2><p>Selon les conditions prévues par le RGPD, vous pouvez demander l’accès à vos données, leur rectification, leur effacement ou la limitation du traitement, et exercer les droits d’opposition et de portabilité lorsqu’ils s’appliquent.</p><p>Adressez votre demande à {contact}. Vous pouvez également déposer une réclamation auprès de la <a href="https://www.cnil.fr/fr/adresser-une-plainte" target="_blank" rel="noopener noreferrer">CNIL</a>.</p></section>
    <section><h2>Sites externes</h2><p>Les liens vers Discord, les réseaux sociaux et, à terme, Steam vous conduisent vers des services distincts. Consultez leurs politiques lorsque vous les utilisez.</p></section>
  </LegalPage>;
}
