import { Link } from "react-router-dom";
import CookiePreferences from "../components/editorial/CookiePreferences";

const contact = <a href="mailto:contact@cobalithstudio.fr">contact@cobalithstudio.fr</a>;
const Placeholder = ({ children }) => <span className="ce-legal-placeholder">{children}</span>;
function LegalPage({ number, title, intro, children }) {
  return <section className="ce-policy ce-wrap">
    <header className="ce-policy-heading"><p className="ce-label">COBALITH STUDIO / {number}</p><h1>{title}</h1><p>{intro}</p><p className="ce-policy-meta">Version du 26 septembre 2026.</p></header>
    <div className="ce-policy-layout">
      <nav aria-label="Documents du site"><Link to="/mentions-legales">01 / Mentions légales</Link><Link to="/conditions-utilisation">02 / Conditions d’utilisation</Link><Link to="/confidentialite">03 / Confidentialité & cookies</Link></nav>
      <div className="ce-policy-copy"><aside className="ce-policy-draft" role="note" aria-label="Document en cours de finalisation"><strong>Attention — document de travail</strong><p>Cobalith Studio est en cours de création. Les champs signalés en rouge sont des données provisoires à remplacer dès l’immatriculation de la micro-entreprise et la finalisation de sa domiciliation parisienne. Le reste du document décrit le fonctionnement prévu du site et du jeu.</p></aside>{children}</div>
    </div>
  </section>;
}
export function LegalNoticePage() {
  return <LegalPage number="01 / INFORMATIONS" title="Mentions légales." intro="L’identité de l’éditeur, les conditions d’hébergement et les règles applicables aux contenus de Cobalith Studio.">
    <section><h2>Éditeur du site</h2><p>Le site cobalithstudio.fr est édité par <Placeholder>Prénom NOM — Entrepreneur individuel (EI), nom commercial Cobalith Studio</Placeholder>, micro-entreprise domiciliée à <Placeholder>000 rue à compléter, 75000 Paris, France</Placeholder>.</p><p>SIREN : <Placeholder>000 000 000</Placeholder> — SIRET : <Placeholder>000 000 000 00000</Placeholder> — immatriculation : <Placeholder>RNE / RCS Paris à compléter</Placeholder> — TVA intracommunautaire : <Placeholder>non applicable ou FR 00 000000000</Placeholder>.</p><p>Courriel : {contact}. Téléphone : <Placeholder>+33 (0)0 00 00 00 00</Placeholder>.</p></section>
    <section><h2>Direction de la publication</h2><p>Le directeur de la publication est <Placeholder>Prénom NOM</Placeholder>, en qualité d’entrepreneur individuel exploitant Cobalith Studio. Il est responsable des contenus publiés sur le site.</p></section>
    <section><h2>Hébergement</h2><p>Le site est hébergé sur une infrastructure propriétaire située en France et administrée directement par l’éditeur. Cette infrastructure repose sur un serveur privé exploité pour le compte exclusif de Cobalith Studio.</p><p>Adresse de l’hébergeur : <Placeholder>adresse professionnelle de domiciliation à compléter, 75000 Paris, France</Placeholder>. Téléphone : <Placeholder>+33 (0)0 00 00 00 00</Placeholder>. Contact technique : {contact}.</p><p>Certains services fonctionnels, notamment l’authentification et la base de données, sont fournis par Supabase. Leur rôle est détaillé dans la <Link to="/confidentialite">politique de confidentialité</Link>.</p></section>
    <section><h2>Objet du site</h2><p>Le site présente Cobalith Studio, l’avancement de <em>Millésime : The Mastercut</em> et des simulateurs consacrés à la vinification, au brassage et aux spiritueux. Il permet également l’accès à un espace de travail privé réservé aux personnes autorisées.</p><p>Le site ne constitue pas une boutique. Aucune commande, transaction, demande de remboursement ou opération de service après-vente concernant le jeu n’y est traitée.</p></section>
    <section><h2>Propriété intellectuelle</h2><p>La structure du site, ses textes, illustrations, photographies, créations graphiques, logos, éléments sonores, simulateurs, bases de données et logiciels, ainsi que les éléments relatifs à <em>Millésime : The Mastercut</em>, sont protégés par les règles françaises et internationales relatives à la propriété intellectuelle.</p><p>Sauf autorisation écrite préalable ou exception légale, toute reproduction, représentation, adaptation, extraction substantielle, diffusion ou exploitation, totale ou partielle, est interdite. Les marques, noms, logos et contenus de tiers restent la propriété de leurs titulaires respectifs.</p></section>
    <section><h2>Liens et signalement</h2><p>Les liens externes mènent vers des services exploités sous la responsabilité de tiers. Cobalith Studio ne contrôle pas en permanence leurs contenus ni leurs conditions. Pour signaler un contenu illicite, une atteinte à un droit ou une erreur : {contact}.</p></section>
  </LegalPage>;
}
export function TermsPage() {
  return <LegalPage number="02 / UTILISATION" title="Conditions d’utilisation." intro="Les règles applicables à la consultation du site, aux simulateurs et aux espaces réservés.">
    <section><h2>Champ d’application</h2><p>Les présentes conditions régissent l’accès à cobalithstudio.fr. La navigation sur le site implique leur acceptation dans leur version en vigueur. Elles peuvent évoluer pour tenir compte du développement du projet, des services proposés ou des règles applicables.</p></section>
    <section><h2>Informations sur le projet</h2><p><em>Millésime : The Mastercut</em> est un jeu de simulation et de gestion multijoueur consacré à la production de vins, bières et spiritueux, avec un ancrage particulier dans les savoir-faire français. Les images, fonctionnalités, dates, équilibres et contenus présentés pendant son développement sont indicatifs et peuvent évoluer.</p><p>La roadmap expose des objectifs de développement. Elle ne constitue ni une offre commerciale, ni une garantie de sortie à une date déterminée, ni un engagement sur la présence définitive d’une fonctionnalité.</p></section>
    <section><h2>Simulateurs</h2><p>Les simulateurs proposés ont une finalité ludique, documentaire et exploratoire. Ils simplifient volontairement certains procédés. Leurs résultats ne constituent pas un conseil professionnel, œnologique, brassicole, réglementaire, sanitaire ou commercial et ne doivent pas servir seuls à piloter une production réelle.</p></section>
    <section><h2>Comptes et espace équipe</h2><p>La création d’un compte n’emporte aucun droit automatique d’accès. Les espaces internes sont réservés aux utilisateurs expressément approuvés par Cobalith Studio. Chaque utilisateur veille à l’exactitude de ses informations, à la confidentialité de ses identifiants et signale sans délai tout accès suspect à {contact}.</p><p>Il est interdit de contourner une mesure de sécurité, tester une vulnérabilité sans autorisation, accéder aux données d’un tiers, introduire un code malveillant, saturer le service, extraire massivement des données ou détourner le site de sa finalité. Un accès peut être suspendu ou supprimé en cas d’usage abusif ou de risque pour le service.</p></section>
    <section><h2>Achat, paiement et service après-vente</h2><p>Le jeu a vocation à être commercialisé exclusivement par l’intermédiaire de Steam. Le contrat d’achat, le paiement, la facturation, la livraison numérique, les règles de remboursement et le support lié à la transaction sont gérés dans l’environnement Steam selon les conditions affichées au moment de l’achat.</p><p>Le présent site n’est pas un guichet de vente ou de service après-vente. Toute demande relative à un achat, un paiement, une clé, un téléchargement ou un remboursement doit être adressée au <a href="https://help.steampowered.com/" target="_blank" rel="noopener noreferrer">support Steam</a>. Les règles générales de remboursement sont consultables dans la <a href="https://store.steampowered.com/steam_refunds/" target="_blank" rel="noopener noreferrer">politique de remboursement Steam</a>. Les droits impératifs du consommateur demeurent applicables.</p><p>Les questions portant sur le contenu du jeu, un problème technique propre au jeu ou un signalement communautaire pourront être adressées par les canaux de support indiqués lors de sa commercialisation.</p></section>
    <section><h2>Propriété intellectuelle et licence</h2><p>La consultation du site n’accorde aucun droit de propriété sur les contenus. Un usage personnel et non commercial est autorisé pour la consultation normale. Toute republication, extraction, modification, commercialisation ou intégration dans un autre produit nécessite une autorisation préalable, sous réserve des exceptions prévues par la loi.</p></section>
    <section><h2>Disponibilité et responsabilité</h2><p>Cobalith Studio met en œuvre des moyens raisonnables pour assurer l’accès et la sécurité du site. Des interruptions peuvent néanmoins résulter d’une maintenance, d’une mise à jour, d’un incident réseau, d’une défaillance matérielle ou d’un événement extérieur.</p><p>L’utilisateur reste responsable de son équipement, de sa connexion et de l’usage qu’il fait des informations publiées. Aucune stipulation ne limite les responsabilités qui ne peuvent légalement être exclues ni les droits impératifs des consommateurs.</p></section>
    <section><h2>Droit applicable et contact</h2><p>Les présentes conditions sont soumises au droit français. En cas de difficulté, l’utilisateur est invité à contacter {contact} afin de rechercher une solution amiable. Les règles légales de compétence juridictionnelle, notamment celles protégeant les consommateurs, restent applicables. Les informations sur l’éditeur figurent dans les <Link to="/mentions-legales">mentions légales</Link>.</p></section>
  </LegalPage>;
}
export function PrivacyPage() {
  return <LegalPage number="03 / VOS DONNÉES" title="Confidentialité & cookies." intro="Les données traitées par Cobalith Studio, leurs finalités, leur conservation et vos choix.">
    <section><h2>Responsable du traitement</h2><p>Le responsable des traitements décrits ici est <Placeholder>Prénom NOM — Entrepreneur individuel (EI), Cobalith Studio</Placeholder>, domicilié à <Placeholder>000 rue à compléter, 75000 Paris, France</Placeholder>. Contact dédié : {contact}.</p></section>
    <section><h2>Les données concernées</h2><dl><dt>Contact par e-mail</dt><dd>Adresse d’expédition, contenu du message, pièces jointes éventuelles et informations nécessaires à la réponse. Le site n’intègre pas de formulaire public.</dd><dt>Compte et authentification</dt><dd>Adresse e-mail, identifiant technique, statut d’approbation, rôle, dates techniques du compte et données de session. Le mot de passe est traité par le service d’authentification Supabase et n’est pas accessible en clair à Cobalith Studio.</dd><dt>Espace équipe</dt><dd>Informations, notes, tâches, budgets et fichiers de travail volontairement enregistrés par les membres autorisés, ainsi que les métadonnées nécessaires à leur gestion.</dd><dt>Mesure d’audience avec consentement</dt><dd>Pages et titres consultés, identifiants pseudonymes de visiteur et de session, page d’entrée, domaine référent, paramètres UTM source, medium et campaign, durée active, engagement, profondeur de lecture, catégorie d’appareil, navigateur, système, tranche de largeur, langue, fuseau, type de connexion et indicateurs LCP et CLS.</dd><dt>Journaux techniques</dt><dd>L’infrastructure d’hébergement et les prestataires techniques peuvent traiter des adresses IP, horodatages et informations de requête nécessaires à la sécurité, au diagnostic et à la fourniture du service.</dd></dl></section>
    <section><h2>Finalités et bases légales</h2><p>Les messages sont traités pour répondre aux demandes et assurer le suivi des échanges, sur la base de l’intérêt légitime ou de mesures précontractuelles selon leur objet. Les comptes et espaces réservés sont traités pour fournir et sécuriser le service demandé, exécuter les engagements applicables aux membres et protéger les intérêts légitimes du studio.</p><p>Les journaux techniques servent à maintenir la sécurité et la disponibilité du site sur la base de l’intérêt légitime. La mesure d’audience interne est déclenchée uniquement après un consentement explicite, libre et révocable.</p></section>
    <section><h2>Destinataires et prestataires</h2><p>Les données sont accessibles uniquement aux personnes habilitées de Cobalith Studio selon leurs fonctions. Supabase fournit l’authentification, la base de données et le stockage associés aux comptes, aux espaces internes et à la mesure d’audience. Le prestataire de messagerie traite les échanges adressés au studio.</p><p>Le site public est servi depuis une infrastructure propriétaire administrée par l’éditeur en France. La région Supabase utilisée est <Placeholder>région du projet à confirmer</Placeholder> et le prestataire de messagerie est <Placeholder>prestataire à compléter</Placeholder>. Si un prestataire implique un transfert hors de l’Espace économique européen, les garanties prévues par le RGPD sont appliquées et documentées.</p><p>Aucune donnée d’audience n’est vendue, utilisée à des fins publicitaires ou recoupée avec la navigation sur d’autres sites.</p></section>
    <section><h2>Durées de conservation</h2><p>Les échanges sont conservés pendant le temps nécessaire à leur traitement, puis archivés au maximum trois ans après le dernier contact, sauf obligation légale ou contentieux. Les comptes sont conservés tant qu’ils sont actifs, puis supprimés ou archivés dans un délai raisonnable après leur clôture. Les contenus de l’espace équipe suivent la durée du projet et les besoins de preuve, de sécurité et de gestion interne.</p><p>Les identifiants pseudonymes d’audience sont conservés au maximum treize mois sans prolongation automatique. Les événements d’audience sont supprimés après vingt-cinq mois. Les journaux techniques sont conservés pendant <Placeholder>durée technique à confirmer</Placeholder>. Les sauvegardes suivent les cycles de rétention du service concerné avant leur écrasement.</p></section>
    <section><h2>Cookies et stockage local</h2><p>Le site mémorise votre choix sous la clé « cobalith.cookie-preferences » pendant six mois afin de ne pas solliciter votre décision à chaque visite. Accepter et refuser ont la même durée. Fermer le bandeau ou poursuivre la navigation ne vaut pas consentement.</p><p>Après connexion, Supabase utilise le stockage du navigateur pour maintenir la session. Ce stockage est nécessaire à la fourniture de l’espace demandé. La déconnexion met fin à la session locale sans supprimer le compte.</p><p>Avec votre accord, la mesure d’audience interne envoie les données décrites ci-dessus à Supabase. Elle ne consigne dans la table d’audience ni adresse IP, ni agent utilisateur brut, ni identité du compte, ni contenu saisi, ni URL complète, ni empreinte numérique. Les journaux d’infrastructure de Supabase peuvent néanmoins contenir des données techniques nécessaires à l’exploitation et à la sécurité de ses services.</p><p>Vous pouvez accepter, refuser ou retirer votre consentement à tout moment. Le retrait interrompt la collecte et efface les identifiants d’audience du navigateur ; il n’efface pas automatiquement les statistiques déjà reçues, conservées pendant la durée annoncée.</p><CookiePreferences /></section>
    <section><h2>Vos droits</h2><p>Selon les conditions prévues par le RGPD, vous pouvez demander l’accès à vos données, leur rectification, leur effacement ou la limitation du traitement, et exercer les droits d’opposition et de portabilité lorsqu’ils s’appliquent.</p><p>Adressez votre demande à {contact}. Vous pouvez également déposer une réclamation auprès de la <a href="https://www.cnil.fr/fr/adresser-une-plainte" target="_blank" rel="noopener noreferrer">CNIL</a>.</p></section>
    <section><h2>Sécurité et services externes</h2><p>Cobalith Studio applique des mesures techniques et organisationnelles adaptées au risque : accès restreints, séparation des espaces publics et internes, contrôle des rôles, connexions chiffrées et sauvegardes. Aucun service ne pouvant garantir un risque nul, tout incident suspect peut être signalé à {contact}.</p><p>Les liens vers Steam, Discord, LinkedIn, Instagram ou d’autres plateformes ouvrent des services indépendants qui appliquent leurs propres politiques. Le simple affichage d’un lien ne leur transmet pas de données par Cobalith Studio ; la navigation vers ces services relève ensuite de leurs règles.</p></section>
  </LegalPage>;
}
